---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
  labels:
    app: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
        - name: benchmark
          image: "{{ benchmark_image.image }}"
          env:
          - name: HAIL_DOMAIN
            value: "{{ global.domain }}"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: session-secret-key
              mountPath: /session-secret-key
              readOnly: true
            - name: deploy-config
              mountPath: /deploy-config
              readOnly: true
      volumes:
        - name: session-secret-key
          secret:
            secretName: session-secret-key
        - name: deploy-config
          secret:
            optional: false
            secretName: deploy-config

